# name: Releases

# on: 
#   push:
#     tags:
#     - '*'

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: ncipollo/release-action@v1
#       with:
#         artifacts: "release.tar.gz,foo/*.txt"
#         bodyFile: "log.md"
#         token: ${{ secrets.GITHUB_TOKEN }}

# name: Main

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Generate Changelog
#         # run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
#         run: yarn ; yarn changelog > ${{ github.workflow }}-CHANGELOG.txt
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           body_path: ${{ github.workflow }}-CHANGELOG.txt
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: autorelease
# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - master
# jobs:
#   build:
#     if: github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.labels.*.name), '"autorelease"')
#     runs-on: ubuntu-latest
#     env:
#       manifest_file: 'manifest.yml'
#       changelog_file: 'CHANGELOG.md'
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: master
#       - name: get version
#         id: version
#         run: |
#           sed -n 's/^version:\s\(.*\)$/\1/p' ${{ env.manifest_file }} \
#           | xargs -i echo "::set-output name=version::{}"
#       - name: get changelog
#         id: changelog 
#         run: |
#           changelog=$(echo "${{ steps.version.outputs.version}}" \
#           | xargs -i sed -n '/^#\s\'"{}"'.*$/,/^#\s\([^[:space:]]\+\).*$/{//!p}' ${{ env.changelog_file }})
#           echo $changelog
#           changelog="${changelog//'%'/'%25'}"
#           changelog="${changelog//$'\n'/'%0A'}"
#           changelog="${changelog//$'\r'/'%0D'}"
#           echo "::set-output name=changelog::$changelog" 
#       - name: echo version and changelog
#         run: |
#           echo "${{ steps.version.outputs.version}}"
#           echo "${{ steps.changelog.outputs.changelog }}"
#       - name: Create Release
#         uses: ncipollo/release-action@v1.4.0
#         with:
#           name: ${{ steps.version.outputs.version }}
#           tag: v${{ steps.version.outputs.version }}
#           body: ${{ steps.changelog.outputs.changelog}}
#           draft: false
#           prerelease: false
#           # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).123
#           token: ${{ secrets.GITHUB_TOKEN }}




name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
     changelog_file: 'CHANGELOG.md'
    steps:
    - uses: actions/checkout@v1
    - name: get changelog
      id: changelog
      run: |
          changelog=$(cat CHANGELOG.md)
          echo $changelog
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        # bodyFile: "log.md"
        body: ${{ steps.changelog.outputs.changelog}}
        token: ${{ secrets.GITHUB_TOKEN }}
